In [119]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sn
from sklearn.model_selection import train_test_split, KFold
from sklearn.datasets import load_digits
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression, LinearRegression

In [120]:
digits = load_digits()

In [121]:
train_x, test_x, train_y, test_y = train_test_split(digits.data, digits.target, test_size=.3)

In [122]:
lr = LogisticRegression()
lr.fit(train_x, train_y)
lr.score(test_x, test_y)

c:\Users\flyin\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9592592592592593

In [123]:
lnr = LinearRegression()
lnr.fit(train_x, train_y)
lnr.score(test_x, test_y)

0.5648933483131862

In [124]:
svm = SVC()
svm.fit(train_x, train_y)
svm.score(test_x, test_y)

0.9907407407407407

In [125]:
rf = RandomForestClassifier()
rf.fit(train_x, train_y)
rf.score(test_x, test_y)

0.9833333333333333

In [126]:
kfold = KFold(n_splits=3)
kfold

KFold(n_splits=3, random_state=None, shuffle=False)

In [127]:
for train_index, test_index in kfold.split([1, 2, 3, 4, 5, 6, 7, 8, 9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [128]:
from sklearn.model_selection import StratifiedKFold

folds = StratifiedKFold(n_splits=10)

In [135]:
def get_score(model, train_x, train_y, test_x, test_y):
    model.fit(train_x, train_y)
    return model.score(test_x, test_y)

scores_lg = []
scores_lnr = []
scores_svm = []
scores_rf = []


print('reached for')
for train_index, test_index in kfold.split(digits.data):
    train_x, test_x, train_y, test_y = digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]
    scores_lg.append(get_score(LogisticRegression(), train_x, train_y, test_x, test_y))
    scores_lnr.append(get_score(LinearRegression(), train_x, train_y, test_x, test_y))
    scores_svm.append(get_score(SVC(), train_x, train_y, test_x, test_y))
    scores_rf.append(get_score(RandomForestClassifier(), train_x, train_y, test_x, test_y))

reached for


c:\Users\flyin\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\flyin\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

In [130]:
scores_lg

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [131]:
scores_lnr

[0.5210503111571501, 0.5681424219493626, 0.41943985059688327]

In [132]:
scores_rf

[0.9332220367278798, 0.9482470784641068, 0.9265442404006677]

In [136]:
scores_svm

([0.9666110183639399, 0.9816360601001669, 0.9549248747913188],
 0.9677239844184752)

In [137]:
from sklearn.model_selection import cross_val_score

In [138]:
cross_val_score(LogisticRegression(), digits.data, digits.target)

c:\Users\flyin\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\flyin\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [139]:
cross_val_score(SVC(), digits.data, digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [140]:
cross_val_score(RandomForestClassifier(), digits.data, digits.target)

array([0.92222222, 0.90555556, 0.94986072, 0.95543175, 0.92200557])