In [109]:
import pandas as pd
import numpy as np
from sklearn.pipeline import Pipeline
from sklearn.naive_bayes import GaussianNB
from sklearn.datasets import load_wine

In [110]:
wine_data = load_wine()

dir(wine_data)

['DESCR', 'data', 'feature_names', 'frame', 'target', 'target_names']

In [111]:
wine_df = pd.DataFrame(wine_data.data, columns=wine_data.feature_names)

wine_df.head()

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline  
0                          3.92   1065.0  
1                          3.40   1050.0  
2                          3.17   1185.0  
3                          3.45   1480.0  
4                          2.93    735.0

In [112]:
from sklearn.model_selection import train_test_split

In [113]:
wine_data.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [114]:
train_x, test_x, train_y, test_y = train_test_split(wine_df, wine_data.target, test_size=.65)

train_x

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
31     13.58        1.66  2.36               19.1      106.0           2.86   
71     13.86        1.51  2.67               25.0       86.0           2.95   
136    12.25        4.72  2.54               21.0       89.0           1.38   
104    12.51        1.73  1.98               20.5       85.0           2.20   
59     12.37        0.94  1.36               10.6       88.0           1.98   
..       ...         ...   ...                ...        ...            ...   
18     14.19        1.59  2.48               16.5      108.0           3.30   
122    12.42        4.43  2.73               26.5      102.0           2.20   
148    13.32        3.24  2.38               21.5       92.0           1.93   
154    12.58        1.29  2.10               20.0      103.0           1.48   
106    12.25        1.73  2.12               19.0       80.0           1.65   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
31         3.19                  0.22             1.95             6.90  1.09   
71         2.86                  0.21             1.87             3.38  1.36   
136        0.47                  0.53             0.80             3.85  0.75   
104        1.92                  0.32             1.48             2.94  1.04   
59         0.57                  0.28             0.42             1.95  1.05   
..          ...                   ...              ...              ...   ...   
18         3.93                  0.32             1.86             8.70  1.23   
122        2.13                  0.43             1.71             2.08  0.92   
148        0.76                  0.45             1.25             8.42  0.55   
154        0.58                  0.53             1.40             7.60  0.58   
106        2.03                  0.37             1.63             3.40  1.00   

     od280/od315_of_diluted_wines  proline  
31                           2.88   1515.0  
71                           3.16    410.0  
136                          1.27    720.0  
104                          3.57    672.0  
59                           1.82    520.0  
..                            ...      ...  
18                           2.82   1680.0  
122                          3.12    365.0  
148                          1.62    650.0  
154                          1.55    640.0  
106                          3.17    510.0  

[62 rows x 13 columns]

In [115]:
pipe = Pipeline([
    ('nb', GaussianNB())
])

pipe

Pipeline(steps=[('nb', GaussianNB())])

In [116]:
pipe.fit(train_x, train_y)

Pipeline(steps=[('nb', GaussianNB())])

In [117]:
pipe.predict(test_x)

array([0, 1, 2, 2, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 2, 0, 0, 1, 1, 0, 1, 2,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 2, 2, 1, 1, 2, 0, 0, 1, 0, 1, 1, 2, 2,
       0, 1, 2, 0, 2, 1, 0, 1, 2, 1, 1, 2, 2, 0, 1, 1, 1, 1, 0, 1, 0, 2,
       1, 0, 0, 0, 0, 0, 0, 2, 0, 1, 2, 2, 0, 1, 0, 0, 2, 1, 2, 1, 2, 2,
       0, 0, 2, 1, 0, 0, 1, 1, 1, 0, 2, 0, 1, 2, 1, 0, 1, 2, 0, 0, 2, 1,
       1, 1, 1, 2, 0, 0])

In [118]:
test_y

array([0, 1, 2, 2, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 2, 0, 0, 1, 1, 0, 1, 2,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 2, 2, 1, 1, 2, 0, 0, 1, 1, 1, 1, 2, 2,
       0, 1, 2, 0, 2, 1, 0, 1, 2, 1, 1, 2, 2, 0, 1, 1, 1, 1, 0, 1, 0, 2,
       1, 0, 0, 0, 0, 0, 0, 2, 0, 1, 2, 2, 1, 1, 0, 0, 1, 1, 2, 1, 2, 2,
       0, 0, 2, 1, 0, 0, 1, 1, 1, 0, 2, 1, 1, 2, 1, 0, 1, 1, 0, 0, 2, 1,
       1, 1, 1, 2, 0, 0])

In [119]:
pipe.score(test_x, test_y)

0.9568965517241379